server:
    port: 14000
    
spring:
    application:
        name: gateway-server
        
    cloud:      gateway:
          routes:
          -   id: consumerServer
              uri: lb://consumer-server    #http://127.0.0.1:12000
              predicates: 
              -   Path=/cart/getUserById/**
              filters:
              -   name: Hystrix
                  args:
                      name: fallbackcmd
                      fallbackUri: forward:/fallback
              
eureka:
    client:
        service-url:
            defaultZone: http://eurekaServer13000:13000/eureka/,http://eurekaServer13001:13001/eureka/
            
    instance:
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 15